In [1]:
import pandas as pd

### Creación e indexación de Series
1. Crea una serie con numeros correlativos entre 1 y 12 inclusive (puedes hacerlo como lista o diccionario): 

    - Cambia el índice de la serie anteriormente creada para que comience con el numero 20.


    - Nuevamente cambia el índice de la serie, esta vez con una lista que haga referencia a los meses del año (tenemos 12 elementos como la cantidad de meses del año).

    - Muestra los valores que están en la posición 3 y 8 de mi serie.

    - Muestra los valores que están etiquetados en enero y agosto.
  
    - Muestra sus valores, indices, forma, tamaño y el tipo de elementos de la serie.

In [2]:
#Creo serie como lista
serie_lista=pd.Series(range(1,13))
print(f'La serie desde una lista es:\n{serie_lista}\n')

La serie desde una lista es:
0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
dtype: int64

In [3]:
#Cambio el índice para que comience en el 20
serie_lista.index=range(20, 32)
print(f'La serie con índices desde el 20 es:\n{serie_lista}')

La serie con índices desde el 20 es:
20     1
21     2
22     3
23     4
24     5
25     6
26     7
27     8
28     9
29    10
30    11
31    12
dtype: int64

In [4]:
#Cambio el índice para que sean los meses del año
serie_lista.index=['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre']
print(f'La serie con índices como meses del año es:\n{serie_lista}')

La serie con índices como meses del año es:
enero          1
febrero        2
marzo          3
abril          4
mayo           5
junio          6
julio          7
agosto         8
septiembre     9
octubre       10
noviembre     11
diciembre     12
dtype: int64

In [5]:
#Muestro los valores que están en las posiciones 3 y 8
print(f'Los valores en las posiciones 3 y 8 son:\n{serie_lista[[3,8]]}')

Los valores en las posiciones 3 y 8 son:
abril         4
septiembre    9
dtype: int64

In [ ]:
#Muestro los valores que están etiquetados como 'enero' y 'agosto'
print(f'Los valores etiquetados en enero y agosto son:\n{serie_lista[["enero","agosto"]]}')

Los valores etiquetados en enero y agosto son:
enero     1
agosto    8
dtype: int64

In [ ]:
#Muestro valores, indices, forma, tamaño y tipo de datos
print(f'Los valores de la serie son:\n{serie_lista.values}\n')
print(f'Los índices de la serie son:\n{serie_lista.index}\n')
print(f'La forma de la serie es: {serie_lista.shape}\n')
print(f'El tamaño de la serie es: {serie_lista.size}\n')
print(f'El tipo de datos de la serie es: {serie_lista.dtype}')

Los valores de la serie son:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Los índices de la serie son:
Index(['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio',
       'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'],
      dtype='object')

La forma de la serie es: (12,)

El tamaño de la serie es: 12

El tipo de datos de la serie es: int64

### Indexación
A lo largo de todos los ejercicios de la clase invertida trabajaremos con un *csv* que contiene información de las ventas de un *e-commerce*. En concreto usaremos un DataFrame que se llama `rating-and-performance.csv`. Nos proporciona información detalladas de las características de cada producto, calificaciones, ventas, reseñas y otras métricas para que podamos comprender qué hace que un producto de verano tenga éxito en Wish. Veamos en detalles sus columnas para entender mejor el conjuntos de datos: 


| Columna                      | Descripción                                                                                                    |
|------------------------------|----------------------------------------------------------------------------------------------------------------|
| title                        | El título del producto. (*object*)                                                                      |
| title_orig                   | El título original del producto. (*object*)                                                             |
| price                        | El precio del producto. (*float*)                                                                             |
| retail_price                 | El precio minorista original del producto. (*float*)                                                           |
| currency_buyer               | La moneda del comprador. (*object*)                                                                     |
| units_sold                   | El número de unidades vendidas. (*integer*)                                                                       |
| uses_ad_boosts               | Un indicador de si el producto ha sido promovido mediante anuncios. (*bool*)                                  |
| rating                       | La calificación del producto. (*float*)                                                                       |
| rating_count                 | El número total de calificaciones para el producto. (*integer*)                                                    |
| rating_five_count            | El número de calificaciones de cinco estrellas para el producto. (*integer*)                                       |
| rating_four_count            | El número de calificaciones de cuatro estrellas para el producto. (*integer*)                                      |
| rating_three_count           | El número de calificaciones de tres estrellas para el producto. (*integer*)                                        |
| rating_two_count             | El número de calificaciones de dos estrellas para el producto. (*integer*)                                         |
| rating_one_count             | El número de calificaciones de una estrella para el producto. (*integer*)                                          |
| badges_count                 | El número de insignias asociadas al producto. (*integer*)                                                          |
| badge_local_product          | Un indicador de si el producto es local. (*bool*)                                                             |
| badge_product_quality        | Un indicador de si el producto tiene una insignia de calidad. (*bool*)                                        |
| badge_fast_shipping          | Un indicador de si el producto tiene una insignia de envío rápido. (*bool*)                                   |
| tags                         | Las etiquetas asociadas al producto. (*object*)                                                         |
| product_color                | El color del producto. (*object*)                                                                       |
| product_variation_inventory  | El inventario de la variación del producto. (*integer*)                                                           |
| shipping_option_name         | El nombre de la opción de envío. (*object*)                                                             |
| shipping_option_price        | El precio de la opción de envío. (*float*)                                                                    |
| shipping_is_express          | Un indicador de si la opción de envío es express. (*bool*)                                                    |
| countries_shipped_to         | Los países a los que se envía el producto. (*object*)                                                   |
| inventory_total              | El inventario total del producto. (*integer*)                                                                     |
| has_urgency_banner           | Un indicador de si el producto tiene un banner de urgencia. (*bool*)                                          |
| urgency_text                 | El texto del banner de urgencia. (*object*)                                                             |
| origin_country               | El país de origen del producto. (*object*)                                                              |
| merchant_title               | El título del comerciante. (*object*)                                                                   |
| merchant_name                | El nombre del comerciante. (*object*)                                                                   |
| merchant_info_subtitle       | El subtítulo del comerciante. (*object*)                                                                |
| merchant_rating_count        | El número total de calificaciones para el comerciante. (*integer*)                                                 |
| merchant_has_profile_picture | Un indicador de si el comerciante tiene una imagen de perfil. (*bool*)                                       |
| merchant_profile_picture     | La imagen de perfil del comerciante. (*object*)                                                         |
| product_url                  | La URL del producto. (*object*)                                                                         |
| product_picture              | La imagen del producto. (*object*)                                                                      |
| theme                        | El tema del producto. (*object*)                                                                        |
| crawl_month                  | El mes en que se obtuvo el producto. (*object*)                                                         |


Para seguir prácticando con Pandas os planteamos los siguientes ejercicios: 

1- Abre el fichero de `rating-and-performance` con el método que sea más correcto. Además muestra las 5 primeras filas del *DataFrame*.

In [ ]:
df_rating_and_performance=pd.read_csv('rating-and-performance.csv', index_col=['index'])
df_rating_and_performance.head()

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
index,,,,,,,,,,,,,,,,,,,,,
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,EUR,100,0,3.76,54,26.0,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22,EUR,20000,1,3.45,6135,2269.0,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,8.00,43,EUR,100,0,3.57,14,5.0,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8,EUR,5000,1,4.03,579,295.0,...,23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3,EUR,100,1,3.10,20,6.0,...,14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08

2- Pongamos en práctica el `loc` e `iloc`:

  - Usando el `loc`: 

      - Extraed todas las filas de la columna "price". ¿De qué tipo es el resultado obtenido?

In [ ]:
print(f'Estas son todas las filas de la columna price:\n{df_rating_and_performance.loc[:, "price"]}\n')

print(f'El tipo de dato es: {df_rating_and_performance["price"].dtype}')

Estas son todas las filas de la columna price:
index
0       16.00
1        8.00
2        8.00
3        8.00
4        2.72
        ...
1568     6.00
1569     2.00
1570     5.00
1571    13.00
1572     7.00
Name: price, Length: 1573, dtype: float64

El tipo de dato es: float64

 - Usando el `loc`: 
      - Extraed todas las filas de las columnas "price" y "retail_price". ¿De qué tipo es el resultado obtenido?

In [ ]:
print(f'Todas las filas de las columnas price y retail_price son:\n{df_rating_and_performance.loc[:,["price", "retail_price"]]}')

print(f'El tipo de dato de la columna price es: {df_rating_and_performance["price"].dtype}')
print(f'El tipo de dato de la columna retail_price es: {df_rating_and_performance["retail_price"].dtype}')

Todas las filas de las columnas price y retail_price son:
       price  retail_price
index
0      16.00            14
1       8.00            22
2       8.00            43
3       8.00             8
4       2.72             3
...      ...           ...
1568    6.00             9
1569    2.00            56
1570    5.00            19
1571   13.00            11
1572    7.00             6

[1573 rows x 2 columns]
El tipo de dato de la columna price es: float64
El tipo de dato de la columna retail_price es: int64

  - Usando el `loc`: 
      - Extraed las filas pares, de las columnas "rating", "rating_count", "rating_five_count", "rating_four_count", "rating_three_count", "rating_two_count", "rating_one_count".

In [ ]:
df_rating_and_performance.loc[::2, ["rating", "rating_count", "rating_five_count", "rating_four_count", "rating_three_count", "rating_two_count", "rating_one_count"]]

,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count
index,,,,,,,
0,3.76,54,26.0,8.0,10.0,1.0,9.0
2,3.57,14,5.0,4.0,2.0,0.0,3.0
4,3.10,20,6.0,4.0,2.0,2.0,6.0
6,3.84,6742,3172.0,1352.0,971.0,490.0,757.0
8,3.47,15,6.0,2.0,3.0,1.0,3.0
...,...,...,...,...,...,...,...
1564,3.38,414,156.0,58.0,72.0,45.0,83.0
1566,3.54,28,7.0,11.0,4.0,2.0,4.0
1568,4.08,1367,722.0,293.0,185.0,77.0,90.0
1570,3.71,59,24.0,15.0,8.0,3.0,9.0
1572,4.07,14,8.0,3.0,1.0,0.0,2.0

  - Usando el `loc`: 
    - Extraed las las filas cuyo precio sea mayor que 10 y sus unidades vendidas ("units_sold") sea mayor que 5000.

In [ ]:
#Limito a las columnas price y units_sold para lectura más fácil
df_rating_and_performance.loc[(df_rating_and_performance["price"] >10) & (df_rating_and_performance["units_sold"] >5000), ["price", "units_sold"]]

       price  units_sold
index
16      11.0       10000
77      11.0       10000
89      11.0       20000
109     11.0       10000
111     14.0       10000
...      ...         ...
1533    16.0       10000
1534    11.0       20000
1537    11.0       10000
1548    12.0       10000
1558    13.0       10000

[82 rows x 2 columns]

  - Usando el `iloc`: 

    - Extraed todas las filas de la columna "price".

In [ ]:
print(f'Estas son todas las filas de la columna price:\n{df_rating_and_performance.iloc[:,2]}\n')

Estas son todas las filas de la columna price:
index
0       16.00
1        8.00
2        8.00
3        8.00
4        2.72
        ...
1568     6.00
1569     2.00
1570     5.00
1571    13.00
1572     7.00
Name: price, Length: 1573, dtype: float64

- Usando el `iloc`: 
    - Extraed todas las filas de las columnas "price" y "retail_price".

In [ ]:
print(f'Todas las filas de las columnas price y retail_price son:\n{df_rating_and_performance.iloc[:,[2, 3]]}')

Todas las filas de las columnas price y retail_price son:
       price  retail_price
index
0      16.00            14
1       8.00            22
2       8.00            43
3       8.00             8
4       2.72             3
...      ...           ...
1568    6.00             9
1569    2.00            56
1570    5.00            19
1571   13.00            11
1572    7.00             6

[1573 rows x 2 columns]

In [ ]:
#Si creo nueva variable lo puedo visualizar en dataframe
prices=df_rating_and_performance.iloc[:, [2,3]]
prices

       price  retail_price
index
0      16.00            14
1       8.00            22
2       8.00            43
3       8.00             8
4       2.72             3
...      ...           ...
1568    6.00             9
1569    2.00            56
1570    5.00            19
1571   13.00            11
1572    7.00             6

[1573 rows x 2 columns]

- Usando el `iloc` (sacaremos los mismos resultados que con el loc): 
    - Extraed las filas pares, de las columnas "rating", "rating_count", "rating_five_count", "rating_four_count", "rating_three_count", "rating_two_count", "rating_one_count".

In [ ]:
#Visualizo todas las columnas para averiguar en qué índices de columna están las que necesito
df_rating_and_performance.columns
#Veo que necesito los índices del 7 al 13

Index(['title', 'title_orig', 'price', 'retail_price', 'currency_buyer',
       'units_sold', 'uses_ad_boosts', 'rating', 'rating_count',
       'rating_five_count', 'rating_four_count', 'rating_three_count',
       'rating_two_count', 'rating_one_count', 'badges_count',
       'badge_local_product', 'badge_product_quality', 'badge_fast_shipping',
       'tags', 'product_color', 'product_variation_size_id',
       'product_variation_inventory', 'shipping_option_name',
       'shipping_option_price', 'shipping_is_express', 'countries_shipped_to',
       'inventory_total', 'has_urgency_banner', 'urgency_text',
       'origin_country', 'merchant_title', 'merchant_name',
       'merchant_info_subtitle', 'merchant_rating_count', 'merchant_rating',
       'merchant_id', 'merchant_has_profile_picture',
       'merchant_profile_picture', 'product_url', 'product_picture',
       'product_id', 'theme', 'crawl_month'],
      dtype='object')

In [ ]:
df_rating_and_performance.iloc[::2,7:14]

,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,rating_one_count
index,,,,,,,
0,3.76,54,26.0,8.0,10.0,1.0,9.0
2,3.57,14,5.0,4.0,2.0,0.0,3.0
4,3.10,20,6.0,4.0,2.0,2.0,6.0
6,3.84,6742,3172.0,1352.0,971.0,490.0,757.0
8,3.47,15,6.0,2.0,3.0,1.0,3.0
...,...,...,...,...,...,...,...
1564,3.38,414,156.0,58.0,72.0,45.0,83.0
1566,3.54,28,7.0,11.0,4.0,2.0,4.0
1568,4.08,1367,722.0,293.0,185.0,77.0,90.0
1570,3.71,59,24.0,15.0,8.0,3.0,9.0
1572,4.07,14,8.0,3.0,1.0,0.0,2.0

### Creación de columnas
 - Cread una nueva columna donde tengamos la diferencia entre el precio al que vende el e-commerce menos el precio del minorista. Insertad esta columna en la posición dos.

In [ ]:
#Traigo el df para verlo
df_rating=pd.read_csv('rating-and-performance.csv', index_col=['index'])
df_rating.head(3)

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
index,,,,,,,,,,,,,,,,,,,,,
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.0,14,EUR,100,0,3.76,54,26.0,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.0,22,EUR,20000,1,3.45,6135,2269.0,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,8.0,43,EUR,100,0,3.57,14,5.0,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08

In [ ]:
#Creo columna con .insert() para poder elegir dónde colocarla y que no se pierda entre tanta información
df_rating.insert(4,'price_difference', df_rating['price'] - df_rating['retail_price'])
df_rating

,title,title_orig,price,retail_price,price_difference,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
index,,,,,,,,,,,,,,,,,,,,,
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.00,14,2.00,EUR,100,0,3.76,54,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,SSHOUSE Summer Casual Sleeveless Soirée Party ...,Women's Casual Summer Sleeveless Sexy Mini Dress,8.00,22,-14.00,EUR,20000,1,3.45,6135,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 Nouvelle Arrivée Femmes Printemps et Été ...,2020 New Arrival Women Spring and Summer Beach...,8.00,43,-35.00,EUR,100,0,3.57,14,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T-shirt pour les femmes Mode T...,Hot Summer Cool T Shirt for Women Fashion Tops...,8.00,8,0.00,EUR,5000,1,4.03,579,...,23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,Femmes Shorts d'été à lacets taille élastique ...,Women Summer Shorts Lace Up Elastic Waistband ...,2.72,3,-0.28,EUR,100,1,3.10,20,...,14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1568,Nouvelle Mode Femmes Bohême Pissenlit Imprimer...,New Fashion Women Bohemia Dandelion Print Tee ...,6.00,9,-3.00,EUR,10000,1,4.08,1367,...,5316,4.224605,5b507899ab577736508a0782,0,NaN,https://www.wish.com/c/5d5fadc99febd9356cbc52ee,https://contestimg.wish.com/api/webimage/5d5fa...,5d5fadc99febd9356cbc52ee,summer,2020-08
1569,10 couleurs femmes shorts d'été lacent ceintur...,10 Color Women Summer Shorts Lace Up Elastic W...,2.00,56,-54.00,EUR,100,1,3.07,28,...,4435,3.696054,54d83b6b6b8a771e478558de,0,NaN,https://www.wish.com/c/5eccd22b4497b86fd48f16b4,https://contestimg.wish.com/api/webimage/5eccd...,5eccd22b4497b86fd48f16b4,summer,2020-08
1570,Nouveautés Hommes Siwmwear Beach-Shorts Hommes...,New Men Siwmwear Beach-Shorts Men Summer Quick...,5.00,19,-14.00,EUR,100,0,3.71,59,...,210,3.961905,5b42da1bf64320209fc8da69,0,NaN,https://www.wish.com/c/5e74be96034d613d42b52dfe,https://contestimg.wish.com/api/webimage/5e74b...,5e74be96034d613d42b52dfe,summer,2020-08
1571,Mode femmes d'été sans manches robes col en V ...,Fashion Women Summer Sleeveless Dresses V Neck...,13.00,11,2.00,EUR,100,0,2.50,2,...,31,3.774194,5d56b32c40defd78043d5af9,0,NaN,https://www.wish.com/c/5eda07ab0e295c2097c36590,https://contestimg.wish.com/api/webimage/5eda0...,5eda07ab0e295c2097c36590,summer,2020-08
1572,Pantalon de yoga pour femmes à la mode Slim Fi...,Fashion Women Yoga Pants Slim Fit Fitness Runn...,7.00,6,1.00,EUR,100,1,4.07,14,...,7023,4.235939,5a409cf87b584e7951b2e25f,0,NaN,https://www.wish.com/c/5e857321f53c3d2d8f25e7ed,https://contestimg.wish.com/api/webimage/5e857...,5e857321f53c3d2d8f25e7ed,summer,2020-08